02-09 23:21:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-176]
02-09 23:21:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-176]
02-09 23:24:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-176]
02-09 23:24:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-176]
02-10 11:24:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-176]
02-10 11:24:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-176]
2016-02-14 12:56:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "AKT" не найдена
Table "AKT" not found; SQL statement:
select * from AKT [42102-190]
2016-02-14 13:17:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¢Ð°Ð±Ð»Ð¸Ñ†Ð° "AKT" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð°
Table "AKT" not found; SQL statement:
select * from PUBLIC.AKT [42102-191]
2016-02-14 13:17:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¢Ð°Ð±Ð»Ð¸Ñ†Ð° "AKT" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð°
Table "AKT" not found; SQL statement:
select * from PUBLIC.AKT [42102-191]
2016-02-14 13:19:16 database: wrong user or password; user: "SA"
org.h2.message.DbException: Ð�ÐµÐ²ÐµÑ€Ð½Ð¾Ðµ Ð¸Ð¼Ñ� Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ� Ð¸Ð»Ð¸ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
Wrong user name or password [28000-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.prog_matik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:17)
	at ru.prog_matik.java.pregis.Main.main(Main.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Ð�ÐµÐ²ÐµÑ€Ð½Ð¾Ðµ Ð¸Ð¼Ñ� Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ� Ð¸Ð»Ð¸ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
Wrong user name or password [28000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 24 more
2016-02-14 13:23:37 database: wrong user or password; user: "PREGIS"
org.h2.message.DbException: Ð�ÐµÐ²ÐµÑ€Ð½Ð¾Ðµ Ð¸Ð¼Ñ� Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ� Ð¸Ð»Ð¸ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
Wrong user name or password [28000-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.prog_matik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:17)
	at ru.prog_matik.java.pregis.Main.main(Main.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Ð�ÐµÐ²ÐµÑ€Ð½Ð¾Ðµ Ð¸Ð¼Ñ� Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»Ñ� Ð¸Ð»Ð¸ Ð¿Ð°Ñ€Ð¾Ð»ÑŒ
Wrong user name or password [28000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 24 more
2016-02-14 13:23:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¢Ð°Ð±Ð»Ð¸Ñ†Ð° "AKT" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½Ð°
Table "AKT" not found; SQL statement:
select * from PUBLIC.AKT [42102-191]
